-- Chuyển cột id của telemetry_logs sang GENERATED BY DEFAULT để tương thích với Hibernate SEQUENCE generator trên composite ID
ALTER TABLE telemetry_schema.telemetry_logs ALTER COLUMN id SET GENERATED BY DEFAULT;
