-- Migration: V20260925144600__Add_Identity_To_Mua_Profiles_Id.sql
-- Description: Đảm bảo cột id trong mua_schema.mua_profiles tự động sinh theo identity sequence

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'mua_schema'
          AND table_name = 'mua_profiles'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE mua_schema.mua_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100);
    END IF;
END $$;
